remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - documents.md
footer: Copyright notice: All of the worked physics examples are owned by their contributor and can be used only for non-commercial purposes.
style: dark
